version: '3'

services:
  mongodb:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    image: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/db:/data/db
  # everest:
  #   env_file: ./.env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: everest
  #   depends_on: 
  #     - mongodb
  #   ports:
  #     - 5000:5000
  #     - 8000:8000
  #   volumes:
  #     - ./..:/opt/everest
  #   command: /bin/bash
  #   stdin_open: true
  #   tty: true
  #   links:
  #     - mongodb
